### ISSUE TITLE
Zip archive cannot be opened on Linux/KDE with ark

### ISSUE THREAD

**Issue by cthil** [McNetic/PHPZipStreamer#25]
The Zip files served by owncloud (presumably) created by this library cannot be opened with the default KDE 4.14.2 archive program *ark*.

Technical details are in the following bug report: https://github.com/owncloud/core/issues/19205

The Zip file is here: http://thil.de/test.zip

**Comment by McNetic** [comment]
This probably due to issues already fixed in the current ZipStreamer release that is also already incorporated in the current owncloud development branch. I unpacked you zip, put the files on my dev version of owncloud, and downloaded them as a new zip: https://box.speedx.cc/index.php/s/JcrQBuaWDXi37fK. Could you please test if this file can be opened with ark?

**Comment by cthil** [comment]
No, I still get the same error.

![ark1](https://cloud.githubusercontent.com/assets/8024840/9992123/1b39191c-6070-11e5-93c6-c87accf963ca.png)

**Comment by McNetic** [comment]
Funny. After reading ark and libarchive source code, I was wondering why it should go wrong and in the end, I tried it myself with Ark 2.17 on KDE 4.7.4 (Knoppix 7), and both my and your zip file work flawlessly.
My conclusion is, that the problem must lie within ark/libarchive and/or your environment in some way. Therefore, I close this issue (feel free to reopen if you can provide information as to why this is a zipstreamer issue nevertheless).

**Comment by cthil** [comment]
Hm, I checked the repos and we have the latest "stable" installed, which also matches the libarchive and zlib "stable" revisions by their authors:
* ark 4:4.14.2-2 (KDE version tag, ark is at 2.19)
* libarchive13 3.1.2-11+b1
* zlib1g 1:1.2.8.dfsg-2+b1

There is a [Debian Live image](http://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-8.2.0-amd64-kde-desktop.iso). As you did test on different program revisions, this might give you a hint.

**Comment by McNetic** [comment]
It tested with the debian live image. Funy. Obviously, Ark and/or libarchive have a regression. I filed a corresponding bug: https://bugs.kde.org/show_bug.cgi?id=353266
